// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateTweet struct {
	Text string `json:"text"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type MessageOutput struct {
	Message string `json:"message"`
}

type PageInfo struct {
	PageSize    int  `json:"pageSize"`
	HasNextPage bool `json:"hasNextPage"`
}

type PaginationInput struct {
	First int `json:"first"`
}

type RegisterInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
	Picture  string `json:"picture"`
	Username string `json:"username"`
}

type TokenOutput struct {
	Token string `json:"token"`
}

type Tweet struct {
	ID    string  `json:"id"`
	Text  string  `json:"text"`
	User  *User   `json:"user"`
	Likes []*User `json:"likes"`
}

type TweetsPaginationOutput struct {
	PageInfo *PageInfo `json:"pageInfo"`
	Tweets   []*Tweet  `json:"tweets"`
}

type User struct {
	ID       string `json:"id"`
	Username string `json:"username"`
	Email    string `json:"email"`
	Picture  string `json:"picture"`
}
